# Generated by Django 5.1.3 on 2024-11-10 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('tags', models.JSONField()),
                ('body', models.TextField()),
                ('email_subject', models.CharField(max_length=100)),
                ('email_body', models.TextField()),
                ('payment_period', models.DateField()),
                ('account_info', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=200)),
                ('duration', models.DateTimeField()),
                ('min_participants', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
