# Generated by Django 5.1.3 on 2024-11-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_remove_purchasepost_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepost',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasepost',
            name='duration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchasepost',
            name='duration_time',
            field=models.TimeField(),
        ),
    ]
