# Generated by Django 4.2.16 on 2024-11-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchaseapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepost',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
